server {
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html/boxlunch;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}