// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BoxLunch.API.Data;

#nullable disable

namespace BoxLunch.API.Migrations
{
    [DbContext(typeof(VibeDbContext))]
    [Migration("20260407212011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BoxLunch.API.Models.AsignacionRolUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaDeAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistorialDeCambios")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RolDelSistemaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolDelSistemaId");

                    b.ToTable("AsignacionesRolUsuario");
                });

            modelBuilder.Entity("BoxLunch.API.Models.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroNomina")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("BoxLunch.API.Models.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Empleado1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaHoraEntrega")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarEntrega")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificacionNombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Empleado1Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("BoxLunch.API.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Empleado1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDeCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaEntrega")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraEntrega")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarEntrega")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoCancelacionTextoLibre")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PedidoNombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Empleado1Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("BoxLunch.API.Models.RolDelSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDeRol")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RolesDelSistema");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Descripcion = "Acceso completo al sistema",
                            NombreDeRol = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Descripcion = "Gestión de pedidos y notificaciones",
                            NombreDeRol = "Operativo"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Descripcion = "Acceso técnico y diagnóstico del sistema",
                            NombreDeRol = "Desarrollador"
                        });
                });

            modelBuilder.Entity("BoxLunch.API.Models.UsuarioDeAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDeUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsuariosDeAcceso");
                });

            modelBuilder.Entity("BoxLunch.API.Models.AsignacionRolUsuario", b =>
                {
                    b.HasOne("BoxLunch.API.Models.RolDelSistema", "RolDelSistema")
                        .WithMany("Asignaciones")
                        .HasForeignKey("RolDelSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolDelSistema");
                });

            modelBuilder.Entity("BoxLunch.API.Models.Notificacion", b =>
                {
                    b.HasOne("BoxLunch.API.Models.Empleado", "Empleado1")
                        .WithMany()
                        .HasForeignKey("Empleado1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxLunch.API.Models.Empleado", "Empleado")
                        .WithMany("Notificaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("Empleado1");
                });

            modelBuilder.Entity("BoxLunch.API.Models.Pedido", b =>
                {
                    b.HasOne("BoxLunch.API.Models.Empleado", "Empleado1")
                        .WithMany()
                        .HasForeignKey("Empleado1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxLunch.API.Models.Empleado", "Empleado")
                        .WithMany("Pedidos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("Empleado1");
                });

            modelBuilder.Entity("BoxLunch.API.Models.Empleado", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BoxLunch.API.Models.RolDelSistema", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
